services:
  auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - auth_data:/app/auth_service/data

  info_service:
    build:
      context: .
      dockerfile: info_service/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8001
    volumes:
      - info_data:/app/info_service/data
      - uploads:/app/info_service/uploads
      - logs:/app/info_service/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8001
      - API_SERVICE_URL=http://info_service:8002
    depends_on:
      - auth_service
      - info_service

volumes:
  auth_data:
  info_data:
  uploads:
  logs:
