"""001_initial_audit_schema

Revision ID: 1cdc2fcd42ba
Revises:
Create Date: 2026-05-20 10:22:59.650959
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '1cdc2fcd42ba'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('operator_role', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_operator_user_id'), 'audit_logs', ['operator_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_service', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caller_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('query_condition', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('snapshot_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_caller_id'), 'operation_logs', ['caller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_logs_caller_id'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_table('dead_letter_queue')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_operator_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
