"""001_initial_info_schema

Revision ID: cf21b192ab65
Revises:
Create Date: 2026-05-20 10:22:57.765632
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'cf21b192ab65'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('term_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_calendars_term_code'), 'academic_calendars', ['term_code'], unique=True)
    op.create_table('base_info_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_info_items_category'), 'base_info_items', ['category'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_no', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('building', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_no')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('credit', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('assessment_method', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    op.create_table('file_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_resources_owner_user_id'), 'file_resources', ['owner_user_id'], unique=False)
    op.create_table('training_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('major_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('required_course_ids', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_programs_major_code'), 'training_programs', ['major_code'], unique=False)
    op.create_index(op.f('ix_training_programs_program_code'), 'training_programs', ['program_code'], unique=True)
    op.create_table('users_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_no', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('role_ids', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_info_user_no'), 'users_info', ['user_no'], unique=True)
    op.create_index(op.f('ix_users_info_username'), 'users_info', ['username'], unique=True)
    op.create_table('course_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('term_code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('class_no', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('teacher_ids', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_offerings_course_id'), 'course_offerings', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_term_code'), 'course_offerings', ['term_code'], unique=False)
    op.create_table('course_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_course_id', sa.Integer(), nullable=False),
    sa.Column('min_grade', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_prerequisites_course_id'), 'course_prerequisites', ['course_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('avatar_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('course_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_period', sa.Integer(), nullable=False),
    sa.Column('end_period', sa.Integer(), nullable=False),
    sa.Column('week_range', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_schedules_offering_id'), 'course_schedules', ['offering_id'], unique=False)
    op.create_table('teacher_course_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('role_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_course_assignments_offering_id'), 'teacher_course_assignments', ['offering_id'], unique=False)
    op.create_index(op.f('ix_teacher_course_assignments_teacher_id'), 'teacher_course_assignments', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_course_assignments_teacher_id'), table_name='teacher_course_assignments')
    op.drop_index(op.f('ix_teacher_course_assignments_offering_id'), table_name='teacher_course_assignments')
    op.drop_table('teacher_course_assignments')
    op.drop_index(op.f('ix_course_schedules_offering_id'), table_name='course_schedules')
    op.drop_table('course_schedules')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_course_prerequisites_course_id'), table_name='course_prerequisites')
    op.drop_table('course_prerequisites')
    op.drop_index(op.f('ix_course_offerings_term_code'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_course_id'), table_name='course_offerings')
    op.drop_table('course_offerings')
    op.drop_index(op.f('ix_users_info_username'), table_name='users_info')
    op.drop_index(op.f('ix_users_info_user_no'), table_name='users_info')
    op.drop_table('users_info')
    op.drop_index(op.f('ix_training_programs_program_code'), table_name='training_programs')
    op.drop_index(op.f('ix_training_programs_major_code'), table_name='training_programs')
    op.drop_table('training_programs')
    op.drop_index(op.f('ix_file_resources_owner_user_id'), table_name='file_resources')
    op.drop_table('file_resources')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_base_info_items_category'), table_name='base_info_items')
    op.drop_table('base_info_items')
    op.drop_index(op.f('ix_academic_calendars_term_code'), table_name='academic_calendars')
    op.drop_table('academic_calendars')
    # ### end Alembic commands ###
